export const metadata = {
  title: "Terms of Service — ClipGenius",
};

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 900, margin: "0 auto", padding: 24 }}>
      <h1>Terms of Service</h1>
      <p><b>Last updated:</b> {new Date().toLocaleDateString()}</p>

      <h2>1) What ClipGenius is</h2>
      <p>
        ClipGenius is a software tool that helps users upload video files and generate short clips.
        ClipGenius does not claim ownership of user content.
      </p>

      <h2>2) User responsibility</h2>
      <p>
        You confirm you own the content you upload or have permission to use it. You are fully
        responsible for your uploads and for how you use any output generated by the service.
      </p>

      <h2>3) Copyright</h2>
      <p>
        Do not upload copyrighted content without permission. ClipGenius is a tool provider and does
        not encourage infringement.
      </p>

      <h2>4) Deletion</h2>
      <p>
        Uploaded files and generated results may be automatically deleted after 72 hours.
      </p>

      <h2>5) Prohibited use</h2>
      <p>
        You may not use ClipGenius for illegal activities, harassment, or violating intellectual
        property rights.
      </p>

      <h2>6) Disclaimer</h2>
      <p>
        The service is provided “as is”. We do not guarantee results, virality, or uninterrupted uptime.
      </p>

      <h2>7) Contact</h2>
      <p>
        Contact support: <b>support@clipgenius.ai</b>
      </p>
    </div>
  );
}